# Generated by Django 2.2.7 on 2019-12-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_loc',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
